export enum MASTER_ERROR {
    LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
    CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
    HEALTH_DETAILS_NOT_FOUND = 'HEALTH_DETAILS_NOT_FOUND',
    ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND',
    GALLERY_DETAILS_NOT_FOUND = 'GALLERY_DETAILS_NOT_FOUND',
    GOOGLE_RATING_NOT_FOUND = 'GOOGLE_RATING_NOT_FOUND',
    NEWS_MEDIA_NOT_FOUND = 'NEWS_MEDIA_NOT_FOUND',
}
