import { StylesClasses, createStyles } from '@utils/styles'

const styles = createStyles({
  mainWrapper: { maxWidth: '1500px', margin: 'auto' },
  wrapper: {
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    width: '100%',
    padding: '3vw 6vw',
    maxWidth: '1590px',
    gap: '32px',
    justifyContent: 'space-around',
  },
  addTestsWrapper: {
    display: 'flex',
    gap: '4px',
  },
  ItemContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
    maxWidth: '766px',
    borderRadius: '16px',
    overflow: 'hidden',
  },
  creditsWrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    borderRadius: '8px',
    padding: '12px 16px',
    backgroundColor: 'common.white',
  },
  healthCreditsWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  checkCredits: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '20px',
    width: '50%',
    justifyContent: 'end',
  },
  totalCredits: {
    display: 'flex',
    flexDirection: 'column',
  },
  availableCredits: {
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '22px',
  },
  healthCredits: {
    fontWeight: '700',
    fontSize: '16px',
    lineHeight: '23px',
  },
  creditsCheckbox: {
    padding: '0px',
    height: '16px',
    width: '16px',
    color: 'primary.light',
  },
  availCredits: {
    fontWeight: '700',
    fontSize: '18px',
    lineHeight: '16px',
  },
  header: {
    zIndex: '1',
    position: 'fixed',
    borderTopLeftRadius: { md: '8px' },
    top: '0',
    height: '84px',
    width: '100%',
    display: 'flex',
    justifyContent: { xs: 'space-between', md: 'unset' },
    gap: { md: '340px' },
    alignItems: 'center',
    backgroundColor: 'common.white',
    padding: '24px',
    boxSizing: 'border-box',
    boxShadow: '0px -1px 19.6px 0px #00000017',
  },
  heading: {
    color: 'custom.black',
    fontSize: '24px',
    fontWeight: '700',
  },
  closeIcon: {
    fontSize: '24px',
    cursor: 'pointer',
  },
  icon: {
    fontSize: { xs: '16px', md: '20px' },
    color: 'primary.main',
    cursor: 'pointer',
  },
  itemWrapper: {
    width: '100%',
    scrollbarWidth: 'none',
    backgroundColor: 'common.white',
    padding: '0px 24px',
    display: 'flex',
    flexDirection: 'column',
    // gap: '32px',
    // marginBottom: '16px',
    borderRadius: '0px 0px 8px 8px',
  },
  totalCharges: {
    fontSize: '16px',
    padding: '24px 0px 0px 24px',
    fontWeight: '500',
    color: 'custom.green',
  },
  valueAddWrapper: {
    fontSize: '16px',
    fontWeight: '500',
    color: 'custom.green',
  },
  itemHeading: {
    fontSize: { xs: '14px', md: '18px' },
    fontWeight: '600',
    color: 'custom.green',
  },
  addPatient: {
    fontSize: '14px',
    fontWeight: '600',
    color: 'primary.main',
    cursor: 'pointer',
  },
  itemDescWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  itemCard: {
    padding: { xs: '16px 0px', md: '24px 0px' },
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    borderColor: 'rgba(0, 0, 0, 0.12) !important',
  },
  itemInfoWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  itemDescription: {
    // width: '100%',
    fontSize: { xs: '12px', md: '14px' },
    fontWeight: '500',
    color: 'custom.grey',
  },
  pricesWrapper: {
    display: 'flex',
    gap: '8px',
    alignItem: 'center',
    justifyContent: 'flex-end',
  },
  fullPrice: {
    textDecorationLine: 'line-through',
  },
  removeButton: {
    width: '70px',
    height: '26px',
    border: '1px solid',
    borderColor: 'custom.grey',
    color: 'custom.grey',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '500',
    '&:hover': {
      color: 'common.black',
      border: '1px solid',
      borderColor: 'common.black',
      backgroundColor: 'custom.lightGrey',
    },
  },
  sideWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: { xs: 'space-between', md: 'unset' },
    alignItems: 'end',
    gap: '12px',
  },
  reportIcon: {
    width: '20px',
    height: '20px',
    img: {
      objectFit: 'contain',
    },
  },
  description: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  sectionName: {
    color: 'custom.green',
    fontSize: '16px',
    fontWeight: '500',
    lineHeight: '24px',
  },
  sectionIcon: {
    height: '26px',
    width: '26px',
    color: 'custom.grey',
  },
  sectionWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    width: '100%',
  },
  sectionHeading: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  divider: {
    margin: '24px 0px',
  },
  patientDetailsWrapper: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    justifyContent: 'space-between',
  },
  linksWrapper: {
    width: '100%',
    height: { xs: '48px', md: '72px' },
    padding: '24px',
    backgroundColor: 'primary.light',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-between',
    borderRadius: '8px 8px 0px 0px',
  },

  image: {
    width: '100%',
    height: '46px',
    img: {
      objectFit: 'contain',
    },
    display: { xs: 'none', md: 'block' },
  },
  addMoreLink: {
    color: 'primary.main',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: { xs: '12px', md: '14px' },
    cursor: 'pointer',
  },
  addressSection: {
    display: 'flex',
    padding: '0px 24px',
    flexDirection: 'column',
    maxHeight: '222px',
    overflow: 'scroll',
    scrollbarWidth: 'none',
  },
  addressWrapper: {
    width: '100%',
    borderRadius: '8px',
    overflow: 'hidden',
    maxWidth: { lg: '399px' },
    backgroundColor: 'common.white',
    display: 'flex',
    flexDirection: 'column',
    height: 'max-content',
  },
  summaryWrapper: {
    width: '100%',
    maxWidth: { lg: '399px' },
    backgroundColor: 'common.white',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    height: 'max-content',
  },
  categoryPrice: {
    display: 'flex',
    // margin: 'auto',
    padding: '0px 24px',
    justifyContent: 'space-between',
  },
  slotWrapper: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  totalChargesWrapper: {
    width: '100%',
    maxWidth: { lg: '399px' },
    borderRadius: '8px',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    height: 'max-content',
  },
  button: {
    marginTop: '16px',
    width: { xs: '100%', md: '399px' },
    height: '65px',
    fontWeight: '700',
    fontSize: '20px',
  },
  valuesWrapper: {
    borderRadius: '8px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    marginTop: '16px',
    backgroundColor: 'common.white',
    padding: '24px',
  },
  checkBoxWrapper: {
    width: '222px',
  },
  label: {
    fontWeight: '600',
    fontSize: '16px',
    color: 'custom.green',
  },
  checkbox: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    width: '100%',
  },
  values: {
    fontSize: '16px',
    fontWeight: '500',
    color: 'custom.lightSilver',
    maxWidth: '290px',
    paddingLeft: '31px',
  },
  totalWrapper: {
    padding: '24px',
    height: '60px',
    maxWidth: { lg: '399px' },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'primary.light',
    borderRadius: '0px 0px 8px 8px',
  },
  price: {
    fontWeight: '600',
  },
  discountPrice: {
    color: 'error.main',
  },
  cartIcon: {
    width: '30px',
    height: '30px',
    img: {
      objectFit: 'contain',
    },
  },
  ctaWrapper: {
    display: 'flex',
    justifyContent: { xs: 'space-between', md: 'unset' },
    gap: { md: '92px' },
    alignItems: 'center',
    padding: '16px 20px',
    backgroundColor: 'common.white',
    width: '100%',
    height: '96px',
    boxSizing: 'border-box',
    position: 'fixed',
    bottom: '0',
    boxShadow: '0px -1px 19.6px 0px #00000017',
    borderRadius: { md: '0px 0px 0px 8px' },
  },
  ctaButton: {
    fontSize: { md: '20px' },
    fontWeight: '600',
    height: { xs: '50px', md: '64px' },
  },
  cartMiniSummary: {
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
  },
  checkboxLabel: {
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '21px',
    color: 'custom.lightSilver',
  },
  checkboxContainer: {
    display: 'flex',
    padding: '16px 0px',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'common.white',
  },
  optionIcon: {
    cursor: 'pointer',
    color: 'custom.grey',
    marginRight: '10px',
  },
  profileHolderWrapper: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
  },
  profileDescription: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    backgroundColor: '#eeeeee',
    width: '20%',
    padding: '8px',
    boxSizing: 'border-box',
    fontSize: '14px',
    borderRadius: '4px',
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: 'custom.lightSilver',
    cursor: 'pointer',
    ':hover': {
      color: 'common.black',
    },
    fontSize: { xs: '14px', md: '16px' },
  },
  backIcon: {
    fontSize: { xs: '16px', md: '20px' },
  },
  navigationWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: { xs: '6px', md: 'unset' },
    gap: '8px',
  },
  selectSlotWrapper: {
    display: 'flex',
    alignItems: 'center',
  },
  couponWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingRight: '16px',
    // remove this to make it work
    // pointerEvents: 'none',
    // opacity: '50%',
  },
  couponDeleteIcon: {
    cursor: 'pointer',
  },
  afterCouponSuccessWrapper: {
    display: 'flex',
    gap: '10px',
  },
  couponApplyButton: {
    color: 'primary.main',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
  },
  couponInput: {
    background: 'white',
    border: '0px',
    width: '100%',
    '.MuiOutlinedInput-notchedOutline': {
      border: 'none',
    },
  },
  couponCheckIcon: {
    color: 'green',
  },
})
export type StylesClassNames = StylesClasses<typeof styles>
export default styles
