export { Banner } from './PageBanner'
export { Feature } from './Feature'
export { TestsSection } from './TestsSection'
export { HomeSampleOverview } from './HomeSampleOverview'
export { DiagnosisSection } from './DiagnosisSection'

export type { BannerProps } from './PageBanner'
export type { DiagnosisSectionData } from './DiagnosisSection'
export type { TestsSectionProps } from './TestsSection'
export type { FeatureProps } from './Feature'
