import { StylesClasses, createStyles } from '@utils/styles'

const styles = createStyles({
  mainWrapper: {
    width: '100vw',
    position: 'fixed',
    top: '-16px',
    zIndex: '12',
    overflow: 'none',
    marginTop: '85px',
    backgroundColor: 'common.white',
  },
  options: {
    width: '100%',
    height: '63px',
    padding: '0px 24px',
    borderTop: '1px solid',
    borderColor: 'primary.white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: '18px',
    fontWeight: '600',
    color: 'primary.white',
  },
  wrapper: {
    padding: '0px 3vw',
    maxWidth: '1600px',
    margin: 'auto',
    width: '100%',
    height: '62px',
    borderBottom: '1px solid',
    borderColor: 'custom.lightGrey',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    justifyContent: { xs: 'space-between', lg: 'none' },
    flexDirection: {
      xs: 'row',
      lg: 'row',
    },
  },
  label: {
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: '400',
    height: '100%',
    display: 'flex',
    textWrap: 'nowrap',
    alignItems: 'center',
    color: 'custom.green',
    ':hover': {
      backgroundColor: 'custom.lightMaroon',
      color: 'primary.main',
      fontWeight: '400',
    },
    padding: '13px',
  },
  imageWrapper: {
    display: { lg: 'none' },
    width: '95px',
    height: '49px',
  },
  button: {
    borderRadius: '49px',
    border: '1px solid',
  },
  navListWrapper: {
    marginLeft: '13px',
    display: {
      xs: 'none',
      lg: 'flex',
    },
    height: '100%',
    alignItems: 'center',
    // gap: { lg: '23px' },
    width: '1182px',
  },
  iconButtonWrapper: {
    display: { lg: 'none', color: 'custom.lightBlack' },
  },
  iconsWrapper: {
    display: 'flex',
    gap: '23px',
    padding: '13px',
    alignItems: 'center',
  },
  ShoppingCartOutlinedIcon: {
    fontSize: '27px',
    alignItems: 'center',
    color: 'primary.main',
    cursor: 'pointer',
  },
  PersonIcon: {
    fontSize: '34px',
    borderRadius: '50%',
    color: 'primary.main',
    backgroundColor: 'primary.light',
    cursor: 'pointer',
  },
  loginIcon: {
    fontSize: '34px',
    borderRadius: '50%',
    color: 'primary.main',
    cursor: 'pointer',
  },
  downloadWrapper: {
    display: 'flex',
    gap: '9px',
    height: '100%',
    alignItems: 'center',
    color: 'custom.lightBlack',
    fontWeight: '600',
    flexDirection: 'row',
    textDecoration: 'none',
    borderRadius: '8px',
    padding: '13px',
    '&:hover': {
      backgroundColor: 'custom.lightMaroon',
    },
  },
  downloadButton: {
    fontSize: '16x',
    color: 'custom.lightBlack',
    fontWeight: '400',
    textWrap: 'nowrap',
    textDecoration: 'none',
  },
  buttonWrapper: {
    display: 'flex',
    gap: '12px',
    marginLeft: '13px',
  },
  mainLogo: {
    width: '131px',
    height: '40px',
  },
  drawerComponent: {
    width: '100%',
    textAlign: 'center',
  },
  drawerHeadComponent: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '13px',
    padding: '6px 24px',
  },
  logoImage: {
    width: '132px',
  },
  fileDownloadOutlinedIcon: {
    color: 'custom.lightBlack',
  },
  drawerWrapper: {
    width: '85vw',
    height: 'auto',
    backgroundColor: 'primary.white',
    zIndex: '5',
    overflow: 'scroll',
    marginTop: '20px',
  },
  drawerMount: {
    display: { xl: 'block' },
    '& .MuiDrawer-paper': {
      boxSizing: 'border-box',
      width: '85vw',
      overflowX: 'hidden',
    },
  },
  menu: {},
  image: {
    width: '95px',
    height: '49px',
  },
  logo: {
    display: { lg: 'none' },
    width: '95px',
    height: '49px',
  },
  drawerLogo: { width: '95px', height: '29px' },
  profileOption: {
    right: '0',
    minWidth: 'fit-content',
    marginTop: '-10px',
    maxHeight: '250px',
    borderTop: '0px solid',
  },
})
export type StylesClassNames = StylesClasses<typeof styles>
export default styles
