export enum FILE_UPLOAD_ERROR {
    NOT_AN_IMAGE = 'NOT_AN_IMAGE_ERROR',
    IMAGE_NOT_UPLOADED = 'IMAGE_NOT_UPLOADED_ERROR',
    GENERATE_URL = 'GENERATE_URL_ERROR',
    DELETE_IMAGE = 'DELETE_IMAGE_ERROR',
    NO_FILE_AVAILABLE = 'NO_FILE_AVAILABLE_ERROR',
    NOT_VALID = 'NOT_VALID_ERROR',
    MISSING_FILE = 'MISSING_FILE_ERROR',
    INVALID_FILE_SIZE = 'INVALID_FILE_SIZE_ERROR',
    INVALID_FILE_TYPE = 'INVALID_FILE_TYPE_ERROR',
    INVALID_FILE_HEIGHT_WIDTH = 'INVALID_FILE_HEIGHT_WIDTH_ERROR',
}
