export enum UHID_PROFILE_ERROR {
    PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
    USER_NOT_CREAED = 'USER_NOT_CREATED',
    ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
    ADDRESS_DELETION_FAILED = 'ADDRESS_DELETION_FAILED',
    PROFILE_ACCESS_DENIED = 'PROFILE_ACCESS_DENIED',
    ADDRESS_UPDATE_DENIED = 'ADDRESS_UPDATE_DENIED',
    ADDRESS_DELETE_DENIED = 'ADDRESS_DELETE_DENIED',
}
