export { BuisnessHours } from './BuisnessHours'
export { OtherLabsAndCenters } from './OtherLabsAndCentres'
export { NearbyLocalities } from './NearbyLocalities'
export { CentreOverview } from './CentreOverview'
export { NearbyTags } from './NearbyTags'
export { FeatureSection } from './FeatureSection'
export { RatingCard } from './ratingSection'

export type { BuisnessData } from './BuisnessHours'
export type { CentreOverviewDataProps } from './CentreOverview'
export type { OtherLabsData } from './OtherLabsAndCentres'
export type { NearbyTagsProps } from './NearbyTags'
export type { NearbyLocalitiesData } from './NearbyLocalities'
export type { FeatureSectionProps } from './FeatureSection'
export type { RatingProps } from './ratingSection'
